// Generated by the Base101 calibration UI. Build and flash the ROS firmware after saving.
#ifndef BASE101_CALIBRATION_H
#define BASE101_CALIBRATION_H
#include "calibration_protocol.h"
#define BASE101_CALIBRATION_PARAMETERS ((calibration_parameters_t){ \
    .ax = 0.7, \
    .jx = 1.6, \
    .aw = 3, \
    .jw = 10, \
    .k_icr = 1.5, \
    .radius = 0.0363, \
    .separation = 0.2899, \
    .ramp = 1, \
    .rpm_max = 200, \
    .vx_max = 0.4, \
    .wz_max = 0.8, \
    .lpf = 80, \
    .kp = 0.5, \
    .ki = 0.3, \
    .correction_max = 0.5, \
    .deadband = 0.005, \
    .correction_accel = 2, \
    .correction_jerk = 9.94, \
    .yaw_feedback = 1, \
})
#endif
