'use strict';
const $=id=>document.getElementById(id);
const client=crypto.randomUUID?.().replaceAll('-','') || 'browser_'+Math.random().toString(36).slice(2);
let sequence=0,state=null,schema=null,armed=false,dirty=false,parametersSeen=null;
let busy=false,stopping=false,trialRunning=false,trialStarting=false,pointerDirection=null;
let step=0,recipeIndex=[0,0,0,0],report={results:[],summary:{},recommendation:{}},selectedResult=null;
let lastMCU=null,errorText='',suggestion=null,reportBusy=false,lastSequenceSeen=null;
const keys=new Set(),history=[];
const directionKeys={w:'forward',s:'backward',a:'left',d:'right',ArrowUp:'forward',ArrowDown:'backward',ArrowLeft:'left',ArrowRight:'right'};
const names=['FRONT LEFT','FRONT RIGHT','BACK LEFT','BACK RIGHT'];
const groups={basic:[['ax','Linear acceleration',.01,'m/s²','Faster response ↔ gentler acceleration'],['jx','Linear jerk',.01,'m/s³','Sharper transitions ↔ softer changes in acceleration'],['aw','Yaw acceleration',.01,'rad/s²','Faster turn response ↔ gentler turning'],['jw','Yaw jerk',.01,'rad/s³','Sharper turning transitions ↔ softer onset']],geometry:[['k_icr','Skid coefficient',.01,'ratio','Encoder yaw / gyro yaw, measured on the floor'],['radius','Wheel radius',.0001,'m','Physical geometry for allocation and encoder odometry'],['separation','Wheel separation',.0001,'m','Wheel-center to wheel-center distance']],motor:[['ramp','Hardware ramp',1,'raw','Motor acceleration byte; software shaping remains primary'],['rpm_max','Wheel speed cap',1,'RPM','Limits wheel allocation'],['vx_max','Linear speed cap',.01,'m/s','Within the 0.40 m/s calibration hard ceiling'],['wz_max','Yaw speed cap',.01,'rad/s','Within the 0.80 rad/s calibration hard ceiling']],gyro:[['lpf','Gyro low-pass',1,'Hz','Less noise ↔ less filtering delay; changes restart calibration'],['kp','Yaw proportional gain',.01,'gain','Corrects yaw-rate error when PI is enabled'],['ki','Yaw integral gain',.01,'gain','Corrects persistent yaw-rate error'],['correction_max','Yaw correction cap',.01,'rad/s','Maximum additional yaw command'],['deadband','Yaw error deadband',.001,'rad/s','Ignores small errors around zero'],['correction_accel','Correction acceleration',.01,'rad/s²','Shapes feedback correction separately'],['correction_jerk','Correction jerk',.01,'rad/s³','Softens feedback correction transitions']]};
function notify(message){errorText=message;$('feedback').textContent=message;$('feedback').classList.add('bad');}
function payload(extra={}){return {client,seq:++sequence,...extra};}
async function post(path,data={}){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:AbortSignal.timeout(1800)});const result=await response.json();if(!response.ok || result.ok===false)throw Error(result.error || `Request failed (${response.status})`);return result;}
function fresh(){return !!state?.connected && state.age_ms<1000;}
function active(){return !!state?.trial || !!state?.sequence || trialStarting || trialRunning;}
function clearHeld(){keys.clear();pointerDirection=null;trialRunning=false;document.querySelectorAll('.dpad button').forEach(b=>b.classList.remove('held'));}
async function hardStop(){stopping=true;clearHeld();armed=false;renderControls();try{await post('/api/stop');}catch(e){notify('Stop acknowledgement unavailable: '+e.message);}finally{stopping=false;renderControls();}}
async function release(){clearHeld();if(!armed)return;try{await post('/api/release',payload());}catch(e){notify(e.message);hardStop();}}
function updateSlider(input){const out=input.closest('label').querySelector('output');if(out)out.textContent=Number(input.value).toFixed(Number(input.step)<.001?4:Number(input.step)<.01?3:Number(input.step)<1?2:0)+input.dataset.unit;}
function initializeParameters(){for(const [group,rows] of Object.entries(groups))$(group).innerHTML=rows.map(([id,label,increment,unit,help])=>{const [low,high]=schema.limits[id];return `<label><div class="row">${label}<output>—</output></div><input id="param-${id}" name="${id}" type="range" min="${low}" max="${high}" step="${increment}" data-unit=" ${unit}" aria-label="${label}"><p class="help">${help}</p></label>`;}).join('');$('parameters').querySelectorAll('input[type=range]').forEach(input=>input.addEventListener('input',()=>updateSlider(input)));}
function fillParameters(params){for(const [name,value] of Object.entries(params || {})){const input=$('parameters').elements[name];if(!input)continue;if(input.type==='checkbox')input.checked=!!value;else{input.value=value;updateSlider(input);}}}
function parameterValues(){const values={};for(const name of Object.keys(schema.limits)){const input=$('parameters').elements[name];if(input)values[name]=input.type==='checkbox'?Number(input.checked):Number(input.value);}return values;}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function recipes(){return schema?.recipes.filter(r=>r.step===step) || [];}
function recipe(){return recipes()[recipeIndex[step]];}
const titles=['Wheels up · identify a quiet, responsive baseline','Floor spins · fit skid compensation','Braking · measure the stop','Odometry · verify a physical reference'];
function showStep(index){if(active()){notify('Stop the current trial before changing steps.');return;}step=index;document.querySelectorAll('[data-step]').forEach(g=>g.open=Number(g.dataset.step)===index);document.querySelector(`[data-step="${index}"] .step-content`).append($('step-body'));$('step-number').textContent=String(index+1).padStart(2,'0');$('step-title').textContent=titles[index];$('confirm').checked=false;$('confirm-text').textContent=index===0?'Wheels are off the floor and the robot is securely supported.':'Robot is on the floor with a clear path for this trial.';$('surface-label').hidden=$('payload-label').hidden=index===0;$('reference-label').hidden=index!==3;$('next-step').hidden=index===3;$('next-step').textContent=['Continue to floor spins →','Continue to braking →','Continue to odometry →',''][index];renderRecipe();renderReport();}
function renderRecipe(){const r=recipe();if(!r)return;$('reference-label').hidden=step!==3 || !!r.verification;$('trial-count').textContent=`${recipeIndex[step]+1} / ${recipes().length}`;$('checklist').replaceChildren(...recipes().map((r,i)=>{const li=document.createElement('li');const accepted=report.results.some(result=>result.recipe===r.id && result.analysis.valid && result.observation==='good' && JSON.stringify(result.parameters)===JSON.stringify(state?.status?.parameters));li.className=accepted?'done':i===recipeIndex[step]?'current':'';li.textContent=`${accepted?'✓':i===recipeIndex[step]?'○':'·'} ${r.title}`;return li;}));$('prompt').textContent=`${r.title} · ${r.duration_s.toFixed(1)} s drive, then normal release. ${r.verification?'Gyro-targeted full turn with shaped release. Compare raw encoder yaw against gyro; PI may stay enabled. Complete all ten verification runs.':step===1?'Fit actual encoder / gyro yaw over matching steady windows, with yaw PI off. Rotations are approximately 180°, not precision yaw moves.':step===3?'Measure actual travel on the floor and enter the reference after the trial.':step===0?'Watch physical direction; the MCU scores transients and response.':'Normal shaped release; emergency braking remains separate.'}`;renderControls();}
function renderControls(){const s=state?.status || {},running=active(),ready=fresh() && s.ready && !s.fault;$('enable').disabled=stopping || !ready || (!armed && !s.at_rest);$('enable').textContent=armed?'Disarm / take control':'Enable controls';document.querySelectorAll('.dpad button').forEach(b=>b.disabled=!armed || !ready || running);$('manual-state').textContent=running?'TRIAL':armed?'ARMED':'DISARMED';$('apply').disabled=running || stopping || !fresh() || !s.at_rest || !!s.motion_enabled || !s.features?.includes('full_config');$('calibrate').disabled=running || !fresh();$('trial').disabled=!running && (stopping || !ready || !armed || !s.at_rest || !$('confirm').checked || !s.features?.includes('metrics') || (step>0 && !$('surface').value.trim()));$('single-trial').disabled=running || $('trial').disabled;$('save-settings').disabled=running || armed || dirty || !!state?.saving || !fresh() || !s.at_rest || !!s.motion_enabled;$('trial-prev').disabled=running || recipeIndex[step]===0;$('trial-next').disabled=running || recipeIndex[step]>=recipes().length-1;$('next-step').disabled=running;$('confirm').disabled=running;$('surface').disabled=$('payload').disabled=running;$('candidate').disabled=running || !suggestion || !s.at_rest || !!s.motion_enabled;$('results-export').disabled=armed || !!s.motion_enabled || !report.results.length;$('settings-export').disabled=!s.parameters;$('parameters').querySelectorAll('input').forEach(input=>input.disabled=running || !s.features?.includes('full_config'));const reviewReady=!state?.last_sequence?.result_id || report.results.some(r=>r.id===state.last_sequence.result_id);$('save-review').disabled=!selectedResult || !reviewReady;document.querySelectorAll('[data-review]').forEach(b=>b.disabled=!selectedResult || running || !reviewReady);}
async function drive(){if(!armed || busy || document.hidden)return;busy=true;try{if(trialRunning && !trialStarting){try{await post('/api/presence',payload());}catch(e){if(e.message==='no active trial'){trialRunning=false;return;}throw e;}return;}if(active())return;const directions=new Set(keys);if(pointerDirection)directions.add(pointerDirection);if(!directions.size)return;const vx=((directions.has('forward')?1:0)-(directions.has('backward')?1:0))*Number(document.querySelector('[aria-label="Linear speed"]').value);const wz=((directions.has('left')?1:0)-(directions.has('right')?1:0))*Number(document.querySelector('[aria-label="Turning speed"]').value);await post('/api/drive',payload({vx,wz}));}catch(e){if(keys.size || pointerDirection || trialRunning){notify(e.message);hardStop();}}finally{busy=false;}}
$('enable').onclick=async()=>{if(armed || active()){await hardStop();return;}try{await post('/api/arm',payload());armed=true;errorText='';renderControls();}catch(e){notify(e.message);}};
$('dock-stop').onclick=hardStop;
for(const [className,direction] of [['forward','forward'],['back','backward'],['left','left'],['right','right']]){const button=document.querySelector('.dpad .'+className);button.addEventListener('pointerdown',e=>{if(!armed || active())return;e.preventDefault();button.setPointerCapture(e.pointerId);pointerDirection=direction;button.classList.add('held');drive();});button.addEventListener('pointerup',release);button.addEventListener('pointercancel',hardStop);button.addEventListener('lostpointercapture',()=>{if(pointerDirection===direction)release();});}
window.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();hardStop();return;}if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.ctrlKey||e.altKey||e.metaKey)return;const direction=directionKeys[e.key.length===1?e.key.toLowerCase():e.key];if(direction && armed){e.preventDefault();if(active()){hardStop();return;}keys.add(direction);drive();}});
window.addEventListener('keyup',e=>{const direction=directionKeys[e.key.length===1?e.key.toLowerCase():e.key];if(keys.delete(direction)){if(!keys.size && !pointerDirection)release();else drive();}});
window.addEventListener('blur',()=>{if(armed || active())hardStop();});document.addEventListener('visibilitychange',()=>{if(document.hidden && (armed || active()))hardStop();});window.addEventListener('pagehide',()=>{if(armed || active())navigator.sendBeacon('/api/stop',new Blob(['{}'],{type:'application/json'}));});
async function startRun(sequenceRun){if(active()){await hardStop();return;}if($(sequenceRun?'trial':'single-trial').disabled)return;clearHeld();trialRunning=true;trialStarting=true;renderControls();try{await post(sequenceRun?'/api/sequence':'/api/trial',payload({recipe:recipe().id,step,verification:!!recipe()?.verification,setup_confirmed:$('confirm').checked,surface:$('surface').value,payload:$('payload').value}));errorText='';}catch(error){notify(error.message);await hardStop();}finally{trialStarting=false;}}
$('trial').onclick=()=>startRun(true);$('single-trial').onclick=()=>startRun(false);
$('save-settings').onclick=async()=>{try{const result=await post('/api/save-settings');$('parameter-status').textContent=`Saved ${result.header}. Build and flash the ROS firmware to use these settings.`;}catch(e){notify(e.message);}};
$('trial-prev').onclick=()=>{recipeIndex[step]--;renderRecipe();};$('trial-next').onclick=()=>{recipeIndex[step]++;renderRecipe();};$('next-step').onclick=()=>showStep(step+1);$('confirm').onchange=renderControls;$('surface').oninput=$('payload').oninput=renderReport;
document.querySelectorAll('[data-step]').forEach(group=>group.addEventListener('toggle',()=>{if(!group.open && Number(group.dataset.step)===step && active()){hardStop();return;}if(group.open && Number(group.dataset.step)!==step){if(active()){group.open=false;notify('Stop the current trial before changing steps.');}else showStep(Number(group.dataset.step));}}));
$('calibrate').onclick=async()=>{clearHeld();armed=false;try{await post('/api/calibrate');}catch(e){notify(e.message);}};
$('parameters').addEventListener('input',()=>{dirty=true;$('parameter-status').textContent='Unapplied settings.';});
$('parameters').onsubmit=async e=>{e.preventDefault();try{const result=await post('/api/parameters',parameterValues());fillParameters(result.parameters);dirty=false;parametersSeen=JSON.stringify(result.parameters);$('parameter-status').textContent='Applied in RAM. Save calibration.h, then build and flash the ROS firmware.';}catch(error){notify(error.message);}};
$('reset').onclick=()=>{fillParameters(state?.status?.parameters);dirty=false;$('parameter-status').textContent='Current MCU settings restored in sliders.';};$('settings-export').onclick=()=>download('base101-settings.json',{date:new Date().toISOString(),parameters:state.status.parameters,geometry:state.status.geometry});
async function review(observation){if(!selectedResult)return;try{const ref=$('reference').value;await post('/api/review',{id:selectedResult.id,...(observation && selectedResult.sequence_id?{sequence_id:selectedResult.sequence_id}:{}),observation:observation || selectedResult.observation,notes:$('notes').value,...(ref?{reference_m:Number(ref)}:{})});await loadReport();}catch(e){notify(e.message);}}
document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>review(b.dataset.review));$('save-review').onclick=()=>review();$('results-export').onclick=()=>download('base101-trials.json',report);
function openDock(){ $('bottom-dock').classList.remove('collapsed');$('dock-toggle').textContent='Collapse ⌄';$('dock-toggle').setAttribute('aria-expanded','true');}
$('dock-toggle').onclick=()=>{const collapsed=$('bottom-dock').classList.toggle('collapsed');$('dock-toggle').textContent=collapsed?'Expand ⌃':'Collapse ⌄';$('dock-toggle').setAttribute('aria-expanded',String(!collapsed));};
$('candidate').onclick=()=>{if(!suggestion)return;fillParameters({...state.status.parameters,...suggestion});dirty=true;openDock();$('parameter-status').textContent='Candidate loaded; apply while stopped, then repeat the same test.';};$('keep').onclick=()=>{fillParameters(state?.status?.parameters);dirty=false;$('parameter-status').textContent='Current MCU settings retained.';};
function display(value,places=3){return Number.isFinite(value)?value.toFixed(places):'—';}
function renderReport(){const matching=report.results.filter(r=>r.recipe===recipe()?.id);const last=matching.at(-1);if(last?.id!==selectedResult?.id){selectedResult=last || null;$('notes').value=last?.notes || '';$('reference').value=last?.reference_m || '';}
 document.querySelectorAll('[data-review]').forEach(b=>b.setAttribute('aria-pressed',String(last?.observation===b.dataset.review)));
 const a=last?.analysis || {},m=last?.metrics || {};
 $('result-detail').textContent=last?`${last.complete?'Completed':'Interrupted'} · ${a.valid?'measurement valid':a.reasons.join('; ')}. Encoder yaw ${display(m.encoder_yaw*180/Math.PI,1)}° · gyro yaw ${display(m.gyro_yaw*180/Math.PI,1)}°. ${last.observation==='pending'?'Confirm physical direction below.':''}`:'No recorded result for this trial yet.';
 const floorFit=report.step_recommendations?.find(r=>r.step===1) || report.summary;const v=report.verification_summary || {};const cards=recipe()?.verification?[['TURNS',`${v.count || 0} / 10`,'same settings / floor / payload'],['ODOM YAW ERROR',display(v.error_deg,1)+'°','raw encoder minus gyro · cumulative'],['GYRO TURN TOTAL',display(v.gyro_deg,1)+'°','3600° target after ten turns']]:step===1?[['VALID TRIALS',`${floorFit.count || 0} / 12`,'same settings / surface / payload'],['FITTED k_icr',display(floorFit.median),'encoder / gyro steady yaw'],['RUN SPREAD',display(floorFit.spread*100,1)+'%','total range / median']]:step===2?[['STOP DISTANCE',display(a.stop_distance*100,1)+' cm','encoder · physical slip may differ'],['STOP TIME',display(a.stop_s,2)+' s','normal shaped release'],['TRANSIENT PEAK',display(a.accel_peak,2),'m/s² · commanded / rotational bounds removed']]:step===3?[['ENCODER TRAVEL',display(Math.abs(m.distance))+' m','complete maneuver'],['REFERENCE',display(last?.reference_m)+' m','operator measurement'],['SCALE ERROR',last?.reference_m?display((Math.abs(m.distance)/last.reference_m-1)*100,1)+'%':'—','repeat forward and backward']]:[['KNOCK TRANSIENTS',a.knocks ?? '—','0.8 m/s² threshold · 80 ms separation'],['TRACKING RMS',display(a.tracking_rms),'m/s (linear) or rad/s (turn)'],['RESPONSE TIME',a.response_s>=0?display(a.response_s,2)+' s':'—','time to 90% of first target']];
 $('scores').replaceChildren(...cards.map(([name,value,desc])=>{const box=document.createElement('div');box.className='score';for(const [tag,text] of [['small',name],['b',value],['span',desc]]){const el=document.createElement(tag);el.textContent=text;box.append(el);}return box;}));
 let rec=step===1?report.summary:report.recommendations?.[recipe()?.id] || {};
 if(recipe()?.id==='minimum')rec={suggestion:null,message:a.minimum_speed?`All four wheels tracked at ${a.minimum_speed.toFixed(2)} m/s or above in the air. Recheck under floor friction.`:'No useful speed established; inspect the per-stage wheel RPM.'};
 if(step===1 && rec.surface && (rec.surface!==$('surface').value.trim() || rec.payload!==$('payload').value.trim()))rec={...rec,suggestion:null,message:`Recorded fit is for ${rec.surface} / ${rec.payload || 'unspecified payload'}. Enter matching context to compare it, or collect trials for the new floor/payload.`};
 const stepRec=report.step_recommendations?.find(r=>r.step===step);
 if(stepRec)rec=stepRec;
 if(step===3 && recipe()?.verification)rec=report.verification_summary || {};
 if(rec.historical)rec={...rec,message:rec.message+' Measured with previous settings; load only the proposed value and verify again.'};
 $('step-suggestions').replaceChildren(...(report.step_recommendations || []).map(r=>{const el=document.createElement('p');el.className='help';el.textContent=`${['Wheels up','Floor spins','Braking','Odometry'][r.step]}: ${r.suggestion?Object.entries(r.suggestion).map(([k,v])=>`${k} → ${v}`).join(' · '):r.message}${r.historical?' · previous settings':''}`;return el;}));
 suggestion=rec.suggestion || null;$('recommend-title').textContent=suggestion?'Candidate for comparison':'Next measurement';$('recommend-text').textContent=rec.message || 'Complete and review this trial; repeat the baseline to assess consistency.';$('current-setting').textContent=suggestion?Object.keys(suggestion).map(k=>`${k} = ${state?.status?.parameters?.[k]}`).join(' · '):'Current MCU settings';$('candidate-setting').textContent=suggestion?Object.entries(suggestion).map(([k,v])=>`${k} = ${v}`).join(' · '):'Waiting for comparable runs';$('analysis-title').textContent=['Smoothness versus response','Skid estimate & consistency','Stopping behavior & knocks','Geometry & independent reference'][step];renderControls();}
async function loadReport(){if(reportBusy || state?.trial || state?.sequence)return;reportBusy=true;try{const response=await fetch('/api/trials',{signal:AbortSignal.timeout(1800)});if(response.ok){report=await response.json();renderReport();renderRecipe();}}catch(e){notify(e.message);}finally{reportBusy=false;}}
function render(){const s=state?.status || {},g=s.gyro || {},imu=s.imu || {},motion=s.motion || {};armed=fresh() && state.operator?.armed && state.operator.client===client;if(!armed && !trialStarting){clearHeld();}if(!state.trial && !state.sequence && !trialStarting && !armed)trialRunning=false;
 if(state.last_sequence && state.last_sequence.id!==lastSequenceSeen){lastSequenceSeen=state.last_sequence.id;if(state.last_sequence.step===step){const index=recipes().findIndex(r=>r.id===state.last_sequence.last_recipe);if(index>=0){recipeIndex[step]=index;renderRecipe();}}loadReport();}
 if(state.sequence && state.trial){const index=recipes().findIndex(r=>r.id===state.trial.recipe);if(index>=0 && recipeIndex[step]!==index){recipeIndex[step]=index;renderRecipe();}}
 $('connection').textContent=fresh()?'Connected':'Disconnected';$('connection').className='badge '+(fresh()?'teal':'bad');$('age').textContent=state.age_ms==null?'No telemetry':`${state.age_ms} ms ago`;$('cal-state').textContent=!imu.online?'Waiting for IMU':g.calibrated?'Gyro calibrated':'Keep robot still';$('progress').style.width=Math.min(100,(g.elapsed_ms || 0)/150)+'%';$('cal-detail').textContent=g.calibrated?`Bias ${display(g.bias,5)} rad/s · ${g.samples} samples`:`${display((g.elapsed_ms || 0)/1000,1)} / 15 s stationary · ${g.rejected || 0} rejected windows`;
 $('encoder-speed').textContent=fresh() && motion.measured_valid?display(motion.measured?.[0]):'—';$('gyro-rate').textContent=fresh() && g.fresh?display(g.rate):'—';$('transient-peak').textContent=fresh()?display(s.metrics?.accel_peak,2):'—';$('wheel-health').textContent=`${fresh()?(s.wheels || []).filter(w=>w.fresh).length:0} / 4 FRESH`;
 $('wheels').replaceChildren(...names.map((name,i)=>{const wheel=s.wheels?.[i],box=document.createElement('div');box.className='wheel';const label=document.createElement('div');label.className='name';label.textContent=name+' '+(fresh() && wheel?.fresh?'●':'○');const rpm=document.createElement('b');rpm.textContent=fresh() && wheel?.fresh?display(wheel.rpm,1):'—';const sent=document.createElement('small');sent.textContent=`RPM · SENT ${fresh()?display(wheel?.sent,1):'—'}`;box.append(label,rpm,sent);return box;}));
 if(fresh() && s.parameters && (!parametersSeen || (!dirty && parametersSeen!==JSON.stringify(s.parameters)))){fillParameters(s.parameters);parametersSeen=JSON.stringify(s.parameters);$('parameter-status').textContent='Current MCU settings loaded.';}
 if(s.mcu_us<lastMCU){history.length=0;dirty=false;parametersSeen=null;notify('MCU restarted; recalibration and fresh measurements required.');}
 if(fresh() && s.mcu_us!==lastMCU && motion.shaped){lastMCU=s.mcu_us;history.push({t:s.mcu_us/1e6,vx:motion.requested[0],vshape:motion.shaped[0],vmeasured:motion.measured_valid?motion.measured[0]:null,wz:motion.requested[1],wshape:motion.shaped[1],wmeasured:motion.measured_valid?motion.measured[1]:null,gyro:g.fresh?g.rate:null,accel:imu.valid?Math.hypot(...imu.accel)-9.80665:null});while(history.length>1000 || (history.length>1 && history[0].t<history.at(-1).t-30))history.shift();}
 $('trial').textContent=state.sequence?`Stop step · ${Math.min(state.sequence.index+1,state.sequence.count)} / ${state.sequence.count}`:state.trial?state.trial.phase==='settling'?'Stop trial · ramping down':`Stop trial · ${Math.max(0,state.trial.duration_s-state.trial.elapsed_s).toFixed(1)} s left`:trialStarting?'Starting…':recipe()?.verification?'Run all 10 turns':'Run entire step';$('trial-help').textContent=step>0 && !$('surface').value.trim()?'Enter the floor surface before starting.':'One click runs all subtests, braking between each. Confirm direction once at the end. Stop / Esc aborts the whole sequence; keep this page focused.';$('run-state').textContent=state.sequence?`Subtest ${state.sequence.index+1}/${state.sequence.count} · ${state.trial?.phase || 'braked pause'}`:state.trial?state.trial.phase:state.last_sequence?`${state.last_sequence.complete?'Step completed':'Step interrupted'} · ${state.last_sequence.reason}`:s.fault?`Fault: ${s.stop_reason}`:armed?'Controls armed':'Disarmed';
 if(!errorText){$('feedback').textContent=state.storage_error?'Result storage failed: '+state.storage_error:state.error || (!s.features?.includes('metrics')?'New calibration firmware required for scoring and advanced settings.':'');$('feedback').classList.toggle('bad',!!state.error || !!state.storage_error);}renderControls();plots();}
function plot(id,series,floor){const canvas=$(id),rect=canvas.getBoundingClientRect(),ratio=devicePixelRatio || 1;canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;const c=canvas.getContext('2d');c.scale(ratio,ratio);const w=rect.width,h=rect.height,L=36,B=h-17;if(w<50)return;let cap=floor;for(const point of history)for(const [key] of series)if(Number.isFinite(point[key]))cap=Math.max(cap,Math.abs(point[key])*1.15);const end=history.at(-1)?.t || 30,start=end-30,x=t=>L+(t-start)/30*(w-L),y=v=>8+(cap-v)/(2*cap)*(B-8);c.font='10px monospace';for(const n of [-1,0,1]){c.strokeStyle='#ffffff12';c.beginPath();c.moveTo(L,y(n*cap));c.lineTo(w,y(n*cap));c.stroke();c.fillStyle='#888';c.fillText((n*cap).toFixed(2),0,y(n*cap)+3);}for(const [key,color] of series){c.strokeStyle=color;c.lineWidth=1.5;c.beginPath();let previous=null;for(const point of history){if(!Number.isFinite(point[key])){previous=null;continue;}if(previous==null || point.t-previous>.3)c.moveTo(x(point.t),y(point[key]));else c.lineTo(x(point.t),y(point[key]));previous=point.t;}c.stroke();}c.fillStyle='#888';c.fillText('−30 s',L,h-2);c.fillText('now',w-23,h-2);}
function plots(){plot('linear',[['vx','#aaa'],['vshape','#30dea7'],['vmeasured','#75a9fa']],.1);plot('yaw',[['wz','#aaa'],['wshape','#30dea7'],['wmeasured','#75a9fa'],['gyro','#e8b66a']],.4);plot('accel',[['accel','#e8b66a']],.5);}
async function poll(){try{const response=await fetch('/api/status',{signal:AbortSignal.timeout(1000)});state=await response.json();render();}catch(e){if(armed || trialRunning)hardStop();state={...(state || {}),connected:false,error:e.message};armed=false;clearHeld();render();}finally{setTimeout(poll,100);}}
async function initialize(){try{const response=await fetch('/api/schema');schema=await response.json();initializeParameters();document.querySelectorAll('input[type=range]').forEach(input=>{if(!input.name)input.addEventListener('input',()=>updateSlider(input));});showStep(0);poll();setInterval(drive,100);setInterval(loadReport,1000);}catch(e){notify(e.message);}}
window.addEventListener('resize',plots);initialize();
