#!/usr/bin/env python3
"""Manual robot calibration UI. Linux, Python3 standard library only."""
import argparse
import fcntl
from datetime import datetime, timezone
import http.server
import json
import itertools
import math
import os
from pathlib import Path
import queue
import re
import select
import signal
import termios
import threading
import time
import sys
import uuid
import copy
from urllib.parse import urlsplit

sys.path.insert(0, str(Path(__file__).parent))
from trials import LIMITS, BASIC_LIMITS, INTEGER_PARAMETERS, RECIPES, BY_ID, analyze, summarize, recommend, geometry_summary, verification_summary, step_recommendations


def validate_parameters(values):
    if not isinstance(values, dict) or set(values) not in (set(LIMITS), set(BASIC_LIMITS)):
        raise ValueError("provide the five basic parameters or the complete configuration")
    for name, value in values.items():
        low, high = LIMITS[name]
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ValueError(f"{name} must be a number")
        if not math.isfinite(value) or not low <= value <= high:
            raise ValueError(f"{name} must be finite and between {low} and {high}")
        if name in INTEGER_PARAMETERS and value != int(value):
            raise ValueError(f"{name} must be an integer")
    return values


TRIAL_PRESENCE_TIMEOUT_S = 1.0
TELEMETRY_TIMEOUT_S = 1.0

def calibration_header(parameters):
    values=validate_parameters(parameters)
    if len(values)!=len(LIMITS):raise ValueError('complete calibration parameters required')
    lines=['// Generated by the Base101 calibration UI. Build and flash the ROS firmware after saving.',
           '#ifndef BASE101_CALIBRATION_H','#define BASE101_CALIBRATION_H',
           '#include "calibration_protocol.h"',
           '#define BASE101_CALIBRATION_PARAMETERS ((calibration_parameters_t){ \\']
    lines.extend('    .'+key+' = '+format(values[key],'.9g')+', \\' for key in LIMITS)
    lines+=['})','#endif','']
    return '\n'.join(lines)

class SerialLink:
    """One thread owns all serial I/O, including heartbeat and HTTP requests."""
    def __init__(self, port, data_dir=None, header_path=None):
        self.port = port
        self.header_path = Path(header_path) if header_path else Path(__file__).resolve().parents[2]/"calibration.h"
        self.requests = queue.PriorityQueue(maxsize=16)
        self.request_order = itertools.count()
        self.lock = threading.Lock()
        self.done = threading.Event()
        self.ready = False
        self.error = None
        self.latest = None
        self.received = None
        self.request_sequence = 0
        self.buffer = bytearray()
        self.operator_client = None
        self.operator_sequence = -1
        self.armed = False
        self.intent = None
        self.intent_until = 0
        self.operator_seen = 0
        self.release_pending = False
        self.force_stop = False
        self.recording = False
        self.samples = []
        self.recording_full = False
        self.recorded_at = None
        self.trial = None
        self.sequence = None
        self.last_sequence = None
        self.saving = False
        self.results = []
        self.storage_error = None
        self.data_dir = Path(data_dir) if data_dir else None
        self.persist = queue.Queue()
        if self.data_dir:
            self.data_dir.mkdir(parents=True, exist_ok=True)
            for path in sorted(self.data_dir.glob('*.json'))[-500:]:
                try:
                    result = json.loads(path.read_text())
                    if isinstance(result,dict) and isinstance(result.get('recipe'),str) and result['recipe'] in BY_ID and isinstance(result.get('parameters'),dict) and isinstance(result.get('analysis'),dict): self.results.append(result)
                except (OSError, ValueError, TypeError): pass
        self.results.sort(key=lambda r:r.get('date',''))
        self.writer = threading.Thread(target=self._write_results, daemon=True)
        self.writer.start()
        self.thread = threading.Thread(target=self._run, daemon=True)
        self.thread.start()

    def snapshot(self):
        with self.lock:
            return {"connected": self.ready, "port": self.port, "error": self.error,
                    "age_ms": None if self.received is None else
                    round((time.monotonic() - self.received) * 1000),
                    "status": self.latest,
                    "trial": None if self.trial is None else {k:v for k,v in self.trial.items() if k not in ('samples','parameters')},
                    "sequence":None if self.sequence is None else {k:v for k,v in self.sequence.items() if k not in ('parameters','payload','recipes')},
                    "last_sequence":self.last_sequence,
                    "saving":self.saving,
                    "storage_error": self.storage_error,
                    "operator": {"armed": self.armed, "client": self.operator_client,
                                 "active": self.intent is not None},
                    "recording": {"active": self.recording, "count": len(self.samples),
                                  "full": self.recording_full}}

    def operator(self, action, payload):
        if not isinstance(payload, dict):
            raise ValueError("operator command must be an object")
        client, sequence = payload.get("client"), payload.get("seq")
        if not isinstance(client, str) or not re.fullmatch(r"[a-zA-Z0-9_-]{8,64}", client):
            raise ValueError("invalid operator client")
        if isinstance(sequence, bool) or not isinstance(sequence, int) or not 0 <= sequence <= 2147483647:
            raise ValueError("invalid operator sequence")
        vx, wz = payload.get("vx"), payload.get("wz")
        if action == "drive":
            for name, value, cap in [("vx", vx, .4), ("wz", wz, .8)]:
                if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value) or abs(value) > cap:
                    raise ValueError(f"{name} must be finite and within +/-{cap}")
        with self.lock:
            if self.saving:raise ValueError("wait for settings save to finish")
            if not self.ready:
                raise ConnectionError(self.error or "serial unavailable")
            if client != self.operator_client:
                if action != "arm" or self.armed:
                    raise ValueError("another operator owns the controls")
                self.operator_client, self.operator_sequence = client, -1
            if sequence <= self.operator_sequence:
                raise ValueError("stale operator command")
            self.operator_sequence = sequence
            self.operator_seen = time.monotonic()
            current = self.latest or {}
            if action in ("arm", "drive", "trial", "sequence", "presence"):
                if not current.get("ready") or current.get("fault") or self.received is None or time.monotonic() - self.received > TELEMETRY_TIMEOUT_S:
                    raise ValueError("fresh calibrated IMU and motor feedback required")
            if (self.trial or self.sequence) and action in ('arm','drive','release'):
                self._finish_trial_locked('manual takeover', False)
                self.armed = False; self.intent = None; self.release_pending = False; self.force_stop=True
                raise ValueError('trial cancelled; Stop, then enable manual controls')
            if action == "sequence":
                step=payload.get('step');verification=payload.get('verification',False)
                if isinstance(step,bool) or not isinstance(step,int) or not 0<=step<=3 or not isinstance(verification,bool) or (verification and step!=3): raise ValueError('invalid step sequence')
                if self.sequence or self.trial: raise ValueError('stop the active sequence first')
                recipes=[r['id'] for r in RECIPES if r['step']==step and bool(r.get('verification'))==verification]
                if not recipes: raise ValueError('no subtests for this step')
                for rid in recipes:self._validate_trial_locked(dict(payload,recipe=rid))
                self.sequence={'id':uuid.uuid4().hex,'step':step,'verification':verification,'index':0,'count':len(recipes),
                    'recipes':recipes,'payload':copy.deepcopy(payload),'parameters':copy.deepcopy(current['parameters']),'resume_at':0}
                self._start_trial_locked(dict(payload,recipe=recipes[0]))
            elif action == "trial":
                if self.sequence: raise ValueError('stop the active sequence first')
                self._start_trial_locked(payload)
            elif action == "presence":
                if not self.armed or not (self.trial or self.sequence): raise ValueError('no active trial')
                self.intent_until=time.monotonic()+TRIAL_PRESENCE_TIMEOUT_S
            elif action == "arm":
                if not current.get("at_rest") or current.get("motion_enabled"):
                    raise ValueError("robot must be at rest before arming")
                self.armed = True
            elif action == "drive":
                if not self.armed:
                    raise ValueError("arm controls before driving")
                self.intent = (vx, wz)
                self.intent_until = time.monotonic() + .2
                self.release_pending = False
            elif action == "release":
                self.intent = None
                self.release_pending = True
            else:
                raise ValueError("invalid operator action")
        return {"ok": True}

    def cancel_operator(self):
        with self.lock:
            if self.trial: self._finish_trial_locked('stopped by operator', False)
            self._end_sequence_locked('stopped by operator',False)
            self.armed = False
            self.intent = None
            self.release_pending = False

    def _validate_trial_locked(self,payload):
        current=self.latest or {}
        recipe_id=payload.get('recipe')
        if not isinstance(recipe_id,str): raise ValueError('invalid trial recipe')
        recipe = BY_ID.get(recipe_id)
        if not recipe: raise ValueError('unknown trial')
        if not self.armed or self.trial or not current.get('at_rest') or current.get('motion_enabled'):
            raise ValueError('arm at rest before starting a trial')
        if payload.get('setup_confirmed') is not True: raise ValueError('confirm trial setup')
        if not {'metrics','bounded_trial','full_config'} <= set(current.get('features', [])):
            raise ValueError('flash the new calibration firmware for automatic trials')
        if not recipe.get('verification') and (current.get('yaw_feedback') or current['parameters'].get('yaw_feedback')):
            raise ValueError('disable yaw PI while identifying the baseline')
        if not current.get('gyro', {}).get('fresh') or len(current.get('wheels', [])) != 4 or any(not w.get('fresh') for w in current['wheels']):
            raise ValueError('fresh sensor and wheel telemetry required')
        params = current['parameters']
        if any(abs(s['vx'])>params['vx_max'] or abs(s['wz'])>params['wz_max'] for s in recipe['stages']):
            raise ValueError('trial exceeds configured body limits')
        for stage in recipe['stages']:
            peak=(abs(stage['vx'])+abs(stage['wz'])*params['k_icr']*params['separation']/2)/params['radius']*60/(2*math.pi)
            if peak>params['rpm_max']: raise ValueError('trial would saturate configured wheel limits')
        surface=payload.get('surface',''); load=payload.get('payload','')
        if not isinstance(surface,str) or not isinstance(load,str) or max(len(surface),len(load))>100: raise ValueError('invalid surface/payload notes')
        if recipe['step']>0 and not surface.strip(): raise ValueError('record the floor surface')
        return recipe,current,params,surface,load

    def _start_trial_locked(self,payload):
        recipe,current,params,surface,load=self._validate_trial_locked(payload)
        self.trial={'id':uuid.uuid4().hex,'recipe':recipe['id'],'phase':'preparing','firmware':current.get('firmware'),'geometry':copy.deepcopy(current.get('geometry',{})),
            'elapsed_s':0,'duration_s':recipe['duration_s'],'parameters':copy.deepcopy(params),
            'surface':surface.strip(),'payload':load.strip(),'samples':[], 'started':time.monotonic(),
            'date':datetime.now(timezone.utc).isoformat(),'last_mcu':current['mcu_us']}
        self.intent_until=time.monotonic()+TRIAL_PRESENCE_TIMEOUT_S
        if self.sequence:
            self.trial.update(sequence_id=self.sequence['id'],sequence_index=self.sequence['index'])

    def _end_sequence_locked(self,reason,complete):
        if self.sequence:
            self.last_sequence={k:v for k,v in self.sequence.items() if k not in ('parameters','payload','recipes')}
            last=self.results[-1] if self.results else {}
            self.last_sequence.update(reason=reason,complete=complete,result_id=last.get('id'),last_recipe=last.get('recipe'))
            self.sequence=None

    def _presence_failure_locked(self,now):
        if not self.armed:return 'operator disarmed'
        if now>=self.intent_until:return 'browser keepalive expired (1 s)'
        if self.received is None or now-self.received>TELEMETRY_TIMEOUT_S:return 'MCU telemetry expired (1 s)'
        return None

    def _sequence_tick_locked(self):
        if not self.sequence or self.trial: return None
        now=time.monotonic();status=self.latest or {};seq=self.sequence
        reason=self._presence_failure_locked(now)
        if not reason and (not status.get('ready') or status.get('fault')):reason='MCU readiness or fault changed'
        if not reason and status.get('parameters')!=seq['parameters']:reason='parameters changed'
        if reason:
            self._end_sequence_locked(reason,False)
            self.armed=False;self.intent=None;return 'stop'
        if now<seq['resume_at']: return None
        if not status.get('at_rest') or status.get('motion_enabled') or status.get('brake_ok_mask')!=15:
            if now>seq['resume_at']+2:
                self._end_sequence_locked('brakes/rest not acknowledged between subtests',False);self.armed=False;return 'stop'
            return None
        try:self._start_trial_locked(dict(seq['payload'],recipe=seq['recipes'][seq['index']]))
        except ValueError as e:
            self._end_sequence_locked(str(e),False);self.armed=False;return 'stop'
        return None

    def save_settings(self):
        with self.lock:
            current=self.latest or {}
            if self.saving or self.armed or self.trial or self.sequence or not current.get('at_rest') or current.get('motion_enabled'):raise ValueError('stop and disarm before saving')
            if self.received is None or time.monotonic()-self.received>TELEMETRY_TIMEOUT_S or current.get('brake_ok_mask')!=15:raise ValueError('fresh feedback confirming all four brakes required')
            parameters=validate_parameters(copy.deepcopy(current.get('parameters',{})))
            if len(parameters)!=len(LIMITS):raise ValueError('complete calibration parameters required')
            self.saving=True
        try:
            text=calibration_header(parameters)
            temporary=self.header_path.with_name(self.header_path.name+'.tmp')
            temporary.write_text(text);temporary.replace(self.header_path)
            return {'ok':True,'header':str(self.header_path),'parameters':parameters}
        except OSError as e:raise ValueError('could not write calibration header: '+str(e)) from e
        finally:
            with self.lock:self.saving=False

    def _write_results(self):
        while True:
            result=self.persist.get()
            if result is None: return
            if self.data_dir:
                try:
                    target=self.data_dir/(result['id']+'.json')
                    temporary=target.with_suffix('.tmp')
                    temporary.write_text(json.dumps(result,allow_nan=False))
                    temporary.replace(target)
                except (OSError,ValueError) as exc:
                    with self.lock: self.storage_error=str(exc)

    def _finish_trial_locked(self, reason, complete):
        trial=self.trial
        if not trial:
            self._end_sequence_locked(reason,complete);return
        trial=copy.deepcopy(trial); trial.update(complete=complete,reason=reason,observation='pending')
        trial['metrics']=copy.deepcopy((self.latest or {}).get('metrics',{}))
        recipe=BY_ID[trial['recipe']]; plateaus=[];start=0
        for stage in recipe['stages']:
            end=start+stage['duration_s']
            rows=[s for s in trial['samples'] if end-1<=s['elapsed_s']<end and s['phase']=='drive']
            plateaus.append({'vx':stage['vx'],'wz':stage['wz'],'samples':len(rows),
                 'mean_rpm':[sum(s['rpm'][i] for s in rows)/len(rows) if rows else 0 for i in range(4)]})
            start=end
        trial['plateaus']=plateaus
        trial['analysis']=analyze(trial)
        self.results.append(trial);self.results=self.results[-500:]
        self.persist.put(copy.deepcopy(trial)); self.trial=None;self.intent=None
        if self.sequence:
            self.sequence['index']+=1
            if not complete or self.sequence['index']>=self.sequence['count']:
                self._end_sequence_locked(reason,complete);self.armed=False
            else:self.sequence['resume_at']=time.monotonic()+.5

    def _trial_tick_locked(self):
        trial=self.trial
        if not trial: return None
        now=time.monotonic(); status=self.latest or {}
        reason=self._presence_failure_locked(now)
        if reason:
            self._finish_trial_locked(reason,False);self.armed=False;return 'stop'
        if not status.get('ready') or status.get('fault') or status.get('parameters')!=trial['parameters'] or status.get('mcu_us',0)<trial['last_mcu']:
            self._finish_trial_locked('readiness, parameters or MCU clock changed',False);self.armed=False;return 'stop'
        if trial['phase']=='preparing': return 'prepare_trial'
        elapsed=now-trial['started'];trial['elapsed_s']=elapsed
        if status.get('mcu_us')!=trial['last_mcu']:
            trial['last_mcu']=status['mcu_us']
            wheels=status.get('wheels',[])
            if len(wheels)!=4 or any(not w.get('fresh') for w in wheels) or not status.get('gyro',{}).get('fresh'):
                self._finish_trial_locked('stale wheel or gyro data',False);self.armed=False;return 'stop'
            trial['samples'].append({'mcu_us':status['mcu_us'],'elapsed_s':elapsed,'phase':trial['phase'],
                'rpm':[w['rpm'] for w in wheels], 'motion':status.get('motion',{}),'gyro_rate':status['gyro']['rate'],'imu':copy.deepcopy(status.get('imu',{})),
                'metrics':copy.deepcopy(status.get('metrics',{}))})
        recipe=BY_ID[trial['recipe']]
        target=recipe.get('target_yaw')
        rate=abs(status.get('gyro',{}).get('rate',0));p=trial['parameters']
        # Symmetric jerk-limited stop from the observed yaw rate.
        stop_s=2*math.sqrt(rate/p['jw']) if rate<=p['aw']**2/p['jw'] else rate/p['aw']+p['aw']/p['jw']
        near_target=target is not None and status.get('metrics',{}).get('gyro_yaw',0)>=target-rate*stop_s/2
        if elapsed>=trial['duration_s'] or near_target or trial['phase']=='settling':
            self.intent=None
            if trial['phase']=='drive':
                trial['phase']='settling';trial['released']=now;return 'release'
            if status.get('at_rest') and not status.get('motion_enabled'):
                self._finish_trial_locked('completed',True)
                if not self.sequence:self.armed=False
                return 'stop'
            if now-trial['released']>3:
                self._finish_trial_locked('rest not acknowledged within three seconds',False);self.armed=False;return 'stop'
        else:
            end=0
            for stage in BY_ID[trial['recipe']]['stages']:
                end+=stage['duration_s']
                if elapsed<end: self.intent=(stage['vx'],stage['wz']);break
        return None

    def trial_data(self):
        with self.lock:
            results=copy.deepcopy([{k:v for k,v in r.items() if k!='samples'} for r in self.results])
            parameters=copy.deepcopy((self.latest or {}).get('parameters',{}))
        summary=summarize([r for r in results if r['parameters']==parameters])
        last=results[-1] if results else None
        recommendation=recommend(results,last['recipe'],parameters) if last and BY_ID[last['recipe']]['step']!=1 else summary
        return {'format':'base101-trials-v1','results':results,'summary':summary,'geometry_summary':geometry_summary(results,parameters),'step_recommendations':step_recommendations(results,parameters),'verification_summary':verification_summary(results),'recommendation':recommendation,
                'recommendations':{r['id']:recommend(results,r['id'],parameters) for r in RECIPES if r['step']!=1}}

    def review_trial(self,payload):
        if not isinstance(payload,dict) or payload.get('observation') not in ('failed','tune','good'): raise ValueError('invalid observation')
        notes=payload.get('notes','')
        if not isinstance(notes,str) or len(notes)>500: raise ValueError('invalid notes')
        reference=payload.get('reference_m')
        if reference is not None and (isinstance(reference,bool) or not isinstance(reference,(int,float)) or not math.isfinite(reference) or not .01<=reference<=10): raise ValueError('reference distance must be 0.01–10 m')
        with self.lock:
            result=next((r for r in self.results if r['id']==payload.get('id')),None)
            if result is None: raise ValueError('unknown trial')
            batch=payload.get('sequence_id')
            if batch is not None and (batch!=result.get('sequence_id') or self.sequence):raise ValueError('finish the sequence before reviewing it')
            rows=[r for r in self.results if r.get('sequence_id')==batch] if batch else [result]
            for row in rows:
                row.update(observation=payload['observation'],notes=notes)
                if row['id']==result['id'] and reference is not None:row['reference_m']=reference
                self.persist.put(copy.deepcopy(row))
        return {'ok':True}

    def record(self, action):
        with self.lock:
            if action == "start":
                self.samples = []
                self.recording_full = False
                self.recording = True
                self.recorded_at = datetime.now(timezone.utc).isoformat()
            elif action == "stop":
                self.recording = False
            else:
                raise ValueError("recording action must be start or stop")
            return {"ok": True, "count": len(self.samples)}

    def recording_data(self):
        with self.lock:
            return {"format": "base101-calibration-v2", "recorded_at": self.recorded_at,
                    "port": self.port, "samples": list(self.samples)}

    def request(self, command):
        with self.lock:
            if not self.ready:
                raise ConnectionError(self.error or "handshake in progress")
        result = queue.Queue(maxsize=1)
        try:
            self.requests.put_nowait((0 if command in ("stop", "calibrate") else 1, next(self.request_order), command, result, time.monotonic() + 1))
        except queue.Full as exc:
            raise ConnectionError("serial request queue full") from exc
        try:
            response = result.get(timeout=1.5)
        except queue.Empty as exc:
            raise ConnectionError("serial request deadline exceeded") from exc
        if isinstance(response, Exception):
            raise response
        return response

    def _exchange(self, fd, command):
        self.request_sequence = self.request_sequence % 2147483647 + 1
        outgoing = f"{self.request_sequence} {command}\n".encode("ascii")
        deadline = time.monotonic() + 0.3
        while outgoing:
            remaining = deadline - time.monotonic()
            if remaining <= 0 or not select.select([], [fd], [], remaining)[1]:
                raise TimeoutError("serial write timeout")
            try:
                outgoing = outgoing[os.write(fd, outgoing):]
            except BlockingIOError:
                continue
        while True:
            while b"\n" in self.buffer:
                line, _, rest = self.buffer.partition(b"\n")
                self.buffer = bytearray(rest)
                try:
                    response = json.loads(line)
                except json.JSONDecodeError as exc:
                    raise ConnectionError(f"MCU sent malformed JSON at byte {exc.pos}: {line[max(0, exc.pos - 16):exc.pos + 24]!r}") from exc
                except UnicodeDecodeError as exc:
                    raise ConnectionError("MCU sent invalid UTF-8 telemetry") from exc
                if not isinstance(response, dict) or response.get("id") != self.request_sequence:
                    continue
                if not isinstance(response.get("ok"), bool):
                    raise ConnectionError("invalid protocol reply")
                if response["ok"]:
                    with self.lock:
                        self.latest = response
                        self.received = time.monotonic()
                        if self.recording:
                            self.samples.append(response)
                            if len(self.samples) >= 30000:
                                self.recording = False
                                self.recording_full = True
                return response
            remaining = deadline - time.monotonic()
            if remaining <= 0 or not select.select([fd], [], [], remaining)[0]:
                raise TimeoutError("serial response timeout")
            try:
                chunk = os.read(fd, 4096)
            except BlockingIOError:
                continue
            if not chunk:
                raise ConnectionError("serial disconnected")
            self.buffer.extend(chunk)
            if len(self.buffer) > 8192:
                raise ConnectionError("serial response too long")

    def _run(self):
        fd = None
        original = None
        owned = False
        pending = None
        try:
            fd = os.open(self.port, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
            fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
            fcntl.ioctl(fd, termios.TIOCEXCL)
            owned = True
            original = termios.tcgetattr(fd)
            raw = termios.tcgetattr(fd)
            raw[0] = raw[1] = raw[3] = 0
            raw[2] = termios.CS8 | termios.CREAD | termios.CLOCAL
            raw[4] = raw[5] = termios.B115200
            raw[6][termios.VMIN] = raw[6][termios.VTIME] = 0
            termios.tcsetattr(fd, termios.TCSANOW, raw)
            termios.tcflush(fd, termios.TCIOFLUSH)
            response = self._exchange(fd, "hello 2")
            if not response.get("ok") or response.get("protocol") != 2 or response.get("firmware") != "base101-calibration":
                raise ConnectionError("calibration firmware handshake failed")
            with self.lock:
                self.ready = True
            next_heartbeat = time.monotonic()
            next_drive = 0
            while not self.done.is_set():
                if time.monotonic() >= next_heartbeat:
                    response = self._exchange(fd, "heartbeat")
                    if not response.get("ok") or not response.get("session"):
                        raise ConnectionError("MCU heartbeat lease expired; restart server to reconnect")
                    next_heartbeat = time.monotonic() + 0.1
                control = None
                with self.lock:
                    control=self._sequence_tick_locked()
                    if control is None:control=self._trial_tick_locked()
                    if self.force_stop: control='stop';self.force_stop=False
                    if self.armed and self.intent is None and time.monotonic() - self.operator_seen > 30:
                        self.armed = False
                    if control is None and self.intent is not None and self.armed:
                        if time.monotonic() >= self.intent_until:
                            self.armed = False
                            self.intent = None
                            control = "stop"
                        elif time.monotonic() >= next_drive:
                            vx, wz = self.intent
                            control = f"drive {vx:.17g} {wz:.17g}"
                            next_drive = time.monotonic() + .1
                    elif control is None and self.release_pending:
                        self.release_pending = False
                        control = "release"
                if control == 'prepare_trial':
                    with self.lock: body_measurement=self.trial is not None and BY_ID[self.trial['recipe']]['step']>0
                    response=self._exchange(fd,'measure '+str(int(body_measurement)))
                    if not response.get('ok'): raise ConnectionError('MCU rejected measurement start')
                    with self.lock:
                        trial_id=self.trial['id'] if self.trial else None
                        duration=self.trial['duration_s']+3 if self.trial else 1
                    response=self._exchange(fd,f'bound {math.ceil(duration*1000)}')
                    if not response.get('ok'): raise ConnectionError('MCU rejected trial deadline')
                    with self.lock:
                        if self.trial and self.trial['id']==trial_id:
                            self.trial['phase']='drive';self.trial['started']=time.monotonic()
                    control=None
                if control:
                    response = self._exchange(fd, control)
                    if not response.get("ok"):
                        self.cancel_operator()
                        self._exchange(fd, "stop")
                try:
                    _, _, command, pending, expiry = self.requests.get(timeout=0.01)
                except queue.Empty:
                    continue
                if time.monotonic() >= expiry:
                    pending.put(TimeoutError("request expired before execution"))
                else:
                    pending.put(self._exchange(fd, command))
                pending = None
        except Exception as exc:
            with self.lock:
                self.error = str(exc)
                self._finish_trial_locked('serial connection failed',False)
            if pending is not None:
                pending.put(ConnectionError(str(exc)))
        finally:
            with self.lock:
                self.ready = False
                self.armed = False
                self.intent = None
            if fd is not None:
                try:
                    if owned:
                        self._exchange(fd, "stop")
                except Exception:
                    pass
                try:
                    if original is not None:
                        termios.tcsetattr(fd, termios.TCSANOW, original)
                    if owned:
                        fcntl.ioctl(fd, termios.TIOCNXCL)
                except (OSError, termios.error):
                    pass
                os.close(fd)
            while True:
                try:
                    _, _, _, result, _ = self.requests.get_nowait()
                    result.put(ConnectionError("serial connection closed"))
                except queue.Empty:
                    break

    def close(self):
        self.done.set()
        self.thread.join(timeout=2)
        self.persist.put(None);self.writer.join(timeout=2)


class Handler(http.server.BaseHTTPRequestHandler):
    def log_request(self, code="-", size="-"):
        if isinstance(code, int) and code >= 400:
            super().log_request(code, size)

    def reply(self, code, payload):
        body = json.dumps(payload, allow_nan=False).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        path = urlsplit(self.path).path
        if path == "/api/status":
            self.reply(200, self.server.link.snapshot())
        elif path == "/api/trials":
            self.reply(200,self.server.link.trial_data())
        elif path == "/api/schema":
            self.reply(200, {"protocol": 2, "limits": LIMITS, "vx_max": .4, "wz_max": .8,"recipes":RECIPES})
        elif path == "/api/recording":
            snapshot = self.server.link.snapshot()
            if snapshot.get("operator", {}).get("armed") or (snapshot.get("status") or {}).get("motion_enabled"):
                self.reply(409, {"error": "stop and disarm before downloading a run"})
            else:
                self.reply(200, self.server.link.recording_data())
        elif path in ("/", "/index.html", "/app.js", "/guided.js", "/app.css", "/theme.css"):
            name = "index.html" if path == "/" else path[1:]
            data = (Path(__file__).parent / name).read_bytes()
            self.send_response(200)
            self.send_header("Content-Type", {".html": "text/html; charset=utf-8", ".js": "text/javascript", ".css": "text/css"}[Path(name).suffix])
            self.send_header("Content-Length", str(len(data)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(data)
        else:
            self.reply(404, {"error": "unknown endpoint"})

    def do_POST(self):
        origin = self.headers.get("Origin")
        if origin and urlsplit(origin).netloc != self.headers.get("Host"):
            self.reply(403, {"error": "cross-origin request rejected"})
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            if not 0 <= length <= 2048:
                raise ValueError("request body must be at most 2048 bytes")
            self.connection.settimeout(2)
            payload = json.loads(self.rfile.read(length)) if length else {}
            if self.path in ("/api/arm", "/api/drive", "/api/release", "/api/trial", "/api/sequence", "/api/presence"):
                response = self.server.link.operator(self.path.rsplit("/", 1)[1], payload)
                self.reply(200, response)
                return
            if self.path == '/api/review':
                self.reply(200,self.server.link.review_trial(payload));return
            if self.path == "/api/record":
                if not isinstance(payload, dict):
                    raise ValueError("recording request must be an object")
                self.reply(200, self.server.link.record(payload.get("action")))
                return
            if self.path in ("/api/stop", "/api/calibrate"):
                self.server.link.cancel_operator()
                command = "stop" if self.path == "/api/stop" else "calibrate"
            elif self.path == '/api/save-settings':
                response=self.server.link.save_settings()
                self.reply(200 if response['ok'] else 422,response);return
            elif self.path == "/api/parameters":
                values = validate_parameters(payload)
                with self.server.link.lock:
                    if self.server.link.trial or self.server.link.sequence or self.server.link.saving: raise ValueError('stop the trial or wait for saving before changing parameters')
                    current=self.server.link.latest or {}
                    if len(values)>5 and 'full_config' not in current.get('features',[]): raise ValueError('new firmware required for advanced configuration')
                command = ("set " if len(values)==5 else "config ") + " ".join(format(values[key], ".9g") for key in (BASIC_LIMITS if len(values)==5 else LIMITS))
            else:
                self.reply(404, {"error": "unknown endpoint"})
                return
            response = self.server.link.request(command)
            self.reply(200 if response["ok"] else 422, response)
        except (ValueError, OverflowError) as exc:
            self.reply(400, {"error": str(exc)})
        except (ConnectionError, TimeoutError) as exc:
            self.reply(503, {"error": str(exc)})


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", required=True, help="calibration firmware CDC device")
    parser.add_argument("--bind", default="127.0.0.1")
    parser.add_argument("--http-port", type=int, default=8080)
    parser.add_argument('--data-dir',default=str(Path.cwd()/'calibration-runs'),help='persistent trial result directory')
    parser.add_argument("--header",default=str(Path(__file__).resolve().parents[2]/"calibration.h"),help="generated ROS calibration header")
    args = parser.parse_args()
    link = SerialLink(args.port,args.data_dir,args.header)
    try:
        server = http.server.ThreadingHTTPServer((args.bind, args.http_port), Handler)
        server.link = link
        # Raise in the main thread so cleanup also runs on SIGTERM.
        def terminate(*_):
            raise KeyboardInterrupt
        signal.signal(signal.SIGTERM, terminate)
        print(f"Calibration UI: http://{args.bind}:{args.http_port}/", flush=True)
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            pass
        finally:
            server.server_close()
    finally:
        link.close()


if __name__ == "__main__":
    main()
